services:
  app:
    build:
      context: .
    restart: always
    depends_on:
      - db
    ports:
      - 9800:9800
    environment:
      - DB_URL
      - TOKEN_SECRET
      - ENV
      - GRPC_PORT
      - POSTGRES_PASSWORD
      - POSTGRES_DB

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"

